#!/usr/bin/env python3
"""Bake the hex pakset's ground deliverable from `render.py`.

This script lives next to the asset it generates
(`landscape/grounds/texture-hex-lightmap.{png,dat}`) and writes its
output one directory up so `make` picks the files up.

Output:

  * `texture-hex-lightmap.png` — atlas of per-slope grayscale lightmaps,
    one cell per valid hex slope.  Each cell carries the per-region
    Lambert shading as RGB8 grayscale (5-bit `brightness/16` expanded;
    16 = 1.0× identity → RGB8 132) and the hex silhouette as the alpha
    channel.  Cell size matches the raster tile width (W=128 → 128×128).

  * `texture-hex-lightmap.dat` — pakset descriptor.  One `Image[N][0]`
    entry per valid slope, in raw `slope_t` ascending order; `N` is the
    compact 0..339 index that the engine's hex-aware ground lookup will
    consume (see TODO.md — the engine side is not wired yet).  The
    comment on each line carries the raw slope index and per-corner
    height tuple for human readability.

Climate texture is not regenerated: pak128's existing
`landscape/grounds/texture-climate.png` is biome art with no tile
geometry baked in, so we reuse it unchanged.  The runtime path is
`create_textured_tile(hex_lightmap[slope], climate_texture[c])`.

Run:
    python3 build_pakset.py [--w 128] [--cols 12] [--out-dir <dir>]

Defaults emit into `<repo>/landscape/grounds/`.  The committed
PNG/.dat are the contract makeobj consumes; rerunning this script
should produce a byte-identical diff (a future CI check will enforce
that).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image

import render
from render import hex_synth


def write_dat(path: Path, layout, rows: int, cols: int, sheet_basename: str):
    n = len(layout)
    max_slope = max(slope for slope, _r, _c in layout)
    lines = [
        "#",
        "# Generated by landscape/grounds/texture-hex-lightmap/build_pakset.py from render.py.",
        "# Do not edit by hand — regenerate after changing the canonical renderer.",
        "#",
        "# One Image[<slope_t>][0] entry per normalised hex slope shape.  The .dat",
        "# index is the **raw slope_t value itself** (base-4 per corner: E=1, SE=4,",
        "# SW=16, W=64, NW=256, NE=1024) so the engine's hex-aware ground lookup can",
        f"# call `get_image_ptr(slope - hgt_shift)` directly without a compact-index",
        "# translation table.  The atlas stays packed (sequential cell positions),",
        "# but the index space is sparse: invalid slope_t values (per-edge delta > 1",
        "# or min(corner_heights) != 0) don't appear and the engine reads them as",
        "# IMG_EMPTY — those encodings can't appear on real terrain so the lookup",
        f"# never requests them.  Sparsity: {n} populated entries out of",
        f"# {max_slope + 1} declared image slots.",
        "#",
        "# Per-line comment carries the per-corner height tuple (E SE SW W NW NE).",
        "#",
        "Obj=ground",
        "Name=HexLightTexture",
        "",
        f"# atlas: {cols} cols x {rows} rows, cells named {sheet_basename}.<row>.<col>",
        "",
    ]
    for slope, r, c in layout:
        ch = render.decode_corner_heights(slope)
        lines.append(
            f"Image[{slope}][0]={sheet_basename}.{r}.{c}\t"
            f"# corners=(E={ch[render.E]} SE={ch[render.SE]} "
            f"SW={ch[render.SW]} W={ch[render.W_C]} NW={ch[render.NW]} NE={ch[render.NE]})"
        )
    lines.append("")
    path.write_text("\n".join(lines))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--w", type=int, default=render.DEFAULT_W,
                   help=f"raster tile width (default {render.DEFAULT_W})")
    p.add_argument("--cols", type=int, default=12,
                   help="atlas columns (default 12; 12*12 = 144 cells, 141 valid slopes)")
    p.add_argument("--out-dir", type=Path, default=None,
                   help="output directory (default <repo>/landscape/grounds/)")
    p.add_argument("--basename", default="texture-hex-lightmap",
                   help="base filename for atlas and .dat (default texture-hex-lightmap)")
    args = p.parse_args()

    if args.out_dir is None:
        # script lives in <repo>/landscape/grounds/texture-hex-lightmap/;
        # bake into <repo>/landscape/grounds/ so makeobj picks the files up.
        args.out_dir = Path(__file__).resolve().parent.parent
    args.out_dir.mkdir(parents=True, exist_ok=True)

    geom = hex_synth.HexGeom(raster_w=args.w)
    atlas, layout, rows = hex_synth.build_atlas(
        geom, args.cols,
        lambda s, g: render.render_lightmap(s, geom=g),
    )

    png_path = args.out_dir / f"{args.basename}.png"
    dat_path = args.out_dir / f"{args.basename}.dat"
    Image.fromarray(atlas, mode="RGBA").save(str(png_path))
    write_dat(dat_path, layout, rows, args.cols, args.basename)

    print(f"build_pakset.py: wrote {len(layout)} slope cells into "
          f"{png_path.relative_to(args.out_dir.parent.parent)} "
          f"({args.cols}x{rows} atlas, {atlas.shape[1]}x{atlas.shape[0]} px)",
          file=sys.stderr)
    print(f"build_pakset.py: wrote .dat with {len(layout)} entries -> "
          f"{dat_path.relative_to(args.out_dir.parent.parent)}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
