#!/usr/bin/env python3
"""Bake the hex pakset's grid-border deliverable from `render.py`.

Sibling of `texture-hex-lightmap/build_pakset.py`; same shape (atlas
PNG + sparse-by-raw-slope_t .dat), different per-cell renderer.  This
script lives next to the asset it generates
(`landscape/grounds/borders.{png,dat}`) and writes its output one
directory up so makeobj picks the files up.

Output:

  * `borders.png` — atlas of per-slope grid-line cells, one per valid
    hex slope.  Each cell is the closed 6-edge hex outline at that
    slope's lifted vertices, drawn in pak128 dark-grey on a
    transparent background.

  * `borders.dat` — `Obj=ground`, `Name=Borders`, one
    `Image[<slope_t>][0]` entry per normalised slope, indexed by the
    raw `slope_t` value itself (same convention as
    `HexLightTexture`).  Sparse: 141 valid slopes out of 4096 raw
    values.

Run:
    python3 build_pakset.py [--w 128] [--cols 12] [--out-dir <dir>]

Re-running this script should produce a byte-identical diff against
the committed PNG/.dat (a future CI check will enforce that).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image

import render
from render import hex_synth


def write_dat(path: Path, layout, rows: int, cols: int, sheet_basename: str):
    n = len(layout)
    max_slope = max(slope for slope, _r, _c in layout)
    lines = [
        "#",
        "# Generated by landscape/grounds/borders/build_pakset.py from render.py.",
        "# Do not edit by hand — regenerate after changing the canonical renderer.",
        "#",
        "# One Image[<slope_t>][0] entry per normalised hex slope shape.  The .dat",
        "# index is the **raw slope_t value itself** (base-4 per corner: E=1, SE=4,",
        "# SW=16, W=64, NW=256, NE=1024) so the engine's hex-aware grid-line lookup",
        "# can call `borders->get_image(slope - hgt_shift)` directly without a",
        "# compact-index translation table.  The atlas stays packed (sequential",
        "# cell positions), but the index space is sparse: invalid slope_t values",
        "# (per-edge delta > 1 or min(corner_heights) != 0) don't appear and the",
        "# engine reads them as IMG_EMPTY — those encodings can't appear on real",
        f"# terrain so the lookup never requests them.  Sparsity: {n} populated",
        f"# entries out of {max_slope + 1} declared image slots.",
        "#",
        "# Per-line comment carries the per-corner height tuple (E SE SW W NW NE).",
        "#",
        "Obj=ground",
        "Name=Borders",
        "",
        f"# atlas: {cols} cols x {rows} rows, cells named {sheet_basename}.<row>.<col>",
        "",
    ]
    for slope, r, c in layout:
        ch = hex_synth.decode_corner_heights(slope)
        lines.append(
            f"Image[{slope}][0]={sheet_basename}.{r}.{c}\t"
            f"# corners=(E={ch[hex_synth.E]} SE={ch[hex_synth.SE]} "
            f"SW={ch[hex_synth.SW]} W={ch[hex_synth.W_C]} "
            f"NW={ch[hex_synth.NW]} NE={ch[hex_synth.NE]})"
        )
    lines.append("")
    path.write_text("\n".join(lines))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--w", type=int, default=hex_synth.DEFAULT_W,
                   help=f"raster tile width (default {hex_synth.DEFAULT_W})")
    p.add_argument("--cols", type=int, default=12,
                   help="atlas columns (default 12; 12*12 = 144 cells, 141 valid slopes)")
    p.add_argument("--out-dir", type=Path, default=None,
                   help="output directory (default <repo>/landscape/grounds/)")
    p.add_argument("--basename", default="borders",
                   help="base filename for atlas and .dat (default borders)")
    args = p.parse_args()

    if args.out_dir is None:
        args.out_dir = Path(__file__).resolve().parent.parent
    args.out_dir.mkdir(parents=True, exist_ok=True)

    geom = hex_synth.HexGeom(raster_w=args.w)
    atlas, layout, rows = hex_synth.build_atlas(
        geom, args.cols,
        lambda s, g: render.render_border(s, geom=g),
    )

    png_path = args.out_dir / f"{args.basename}.png"
    dat_path = args.out_dir / f"{args.basename}.dat"
    Image.fromarray(atlas, mode="RGBA").save(str(png_path))
    write_dat(dat_path, layout, rows, args.cols, args.basename)

    print(f"build_pakset.py: wrote {len(layout)} slope cells into "
          f"{png_path.relative_to(args.out_dir.parent.parent)} "
          f"({args.cols}x{rows} atlas, {atlas.shape[1]}x{atlas.shape[0]} px)",
          file=sys.stderr)
    print(f"build_pakset.py: wrote .dat with {len(layout)} entries -> "
          f"{dat_path.relative_to(args.out_dir.parent.parent)}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
