#!/usr/bin/env python3
"""Bake the hex pakset's animated open-water deliverable from `render.py`.

Standalone (doesn't use `hex_synth.bake_pakset`) because water_ani's
atlas axes are `(depth, stage)`, not slope-keyed; at N = 1 for the
non-slope-keyed shape the right factoring isn't obvious yet.

Run:
    python3 build_pakset.py [--w 128] [--cols 16] [--out-dir <dir>]

Re-running should produce a byte-identical diff against the committed
PNG/.dat (a future CI check will enforce that).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

import render
from render import hex_synth, N_DEPTHS, N_STAGES


HEADER_DOC = """\
Animated open-water tile for the hex pakset.  Image[depth][stage]
indexed by depth tier (0..{last_depth}) and animation frame
(0..{last_stage}).  All 6 × 32 = 192 cells declared — wasser_t::display
queries `sea->get_image(depth, stage)` on every depth tier, so missing
cells flicker the sprite out.  Engine clamps the depth axis at
`water_depth_levels = count - 2`; flat-only on slope.  See
landscape/grounds/water_ani/render.py for the renderer and the per-tier
mean-RGB calibration against the legacy pak128 `water_ani.png`.
"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--w", type=int, default=hex_synth.DEFAULT_W,
                   help=f"raster tile width (default {hex_synth.DEFAULT_W})")
    p.add_argument("--cols", type=int, default=16,
                   help="atlas columns (default 16 → 16x12 grid for 192 cells)")
    p.add_argument("--out-dir", type=Path,
                   default=Path(__file__).resolve().parent.parent,
                   help="output directory (default <repo>/landscape/grounds/)")
    args = p.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    geom = hex_synth.HexGeom(raster_w=args.w)
    cols = args.cols

    cells: list[tuple[int, int]] = [
        (d, s) for d in range(N_DEPTHS) for s in range(N_STAGES)
    ]
    rows = (len(cells) + cols - 1) // cols
    cell_w, cell_h = geom.w, geom.h
    atlas = np.zeros((rows * cell_h, cols * cell_w, 4), dtype=np.uint8)

    layout: list[tuple[int, int, int, int]] = []
    for idx, (depth, stage) in enumerate(cells):
        r, c = divmod(idx, cols)
        atlas[r * cell_h:(r + 1) * cell_h, c * cell_w:(c + 1) * cell_w] = (
            render.render_water(stage, depth=depth, geom=geom)
        )
        layout.append((depth, stage, r, c))

    asset_name = "water_ani"
    obj_name = "Water"
    png_path = args.out_dir / f"{asset_name}.png"
    dat_path = args.out_dir / f"{asset_name}.dat"
    Image.fromarray(atlas, mode="RGBA").save(str(png_path))

    doc_body = HEADER_DOC.format(
        last_depth=N_DEPTHS - 1,
        last_stage=N_STAGES - 1,
    ).rstrip("\n")
    doc_lines = [(f"# {ln}" if ln else "#") for ln in doc_body.split("\n")]
    lines = [
        "#",
        f"# Generated by landscape/grounds/{asset_name}/build_pakset.py from render.py.",
        "# Do not edit by hand — regenerate after changing the canonical renderer.",
        "#",
        *doc_lines,
        "#",
        "Obj=ground",
        f"Name={obj_name}",
        "",
        f"# atlas: {cols} cols x {rows} rows, cells named {asset_name}.<row>.<col>",
        "",
    ]
    for depth, stage, r, c in layout:
        lines.append(f"Image[{depth}][{stage}]={asset_name}.{r}.{c}")
    lines.append("")
    dat_path.write_text("\n".join(lines))

    rel_root = Path(__file__).resolve().parents[2]
    print(f"build_pakset.py: wrote {len(layout)} cells into "
          f"{png_path.relative_to(rel_root)} "
          f"({cols}x{rows} atlas, {atlas.shape[1]}x{atlas.shape[0]} px)",
          file=sys.stderr)
    print(f"build_pakset.py: wrote .dat with {len(layout)} entries -> "
          f"{dat_path.relative_to(rel_root)}", file=sys.stderr)


if __name__ == "__main__":
    main()
